from bot.handlers.auth.auth_handler import auth_labeler

BOT_TOKEN = 'vk1.a.SsJM859tCvdOPxeJ8k2X8R9okdEiQg-ArQtVsmRmmEek-lKZCiGr3liy2pedQd6I7WzqU5rGWk9bFZye9CZW-Xm5iDSefRDWJDTOYm3cMh4MURZJfi-BQvyKWYNwEkW1vcIdzC-5gwK0UddYQloen3aoeEyhGHd9wljXZs_R-Pw2URnatHpPRk0sozKliJWhDyixq_zLlMwHmnSww4QBOA'

labelers = [auth_labeler]
